import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import HomeLayout from "@/layouts/home-layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased font-sans`}
    >
      <body>
        <ThemeProvider>
          <HomeLayout>
            {children}
          </HomeLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
